language: node_js
node_js:
- '8'
os:
- linux
- osx
osx_image: xcode9
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-5
    - libcap-dev
before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then source scripts/linux-before-install.sh; fi
install:
- curl https://sh.rustup.rs -sSf | sh -s -- -y
- export PATH=$PATH:$HOME/.cargo/bin
- npm install
- npm install -g eslint eslint-plugin-mocha
- npm run build
script:
- eslint .
- npm test
notifications:
  email: false
