version: 1.0.{build}
init:
- ps: Install-Product node 8.6.0 x64
- ps: choco install make
environment:
  CL: -DDELAYIMP_INSECURE_WRITABLE_HOOKS
install:
- ps: git submodule update --init --recursive; true
- ps: yarn
build_script:
- ps: make build; true
test_script:
- ps: make lint
- ps: make test
- ps: make bench
after_test:
- ps: npm update -g npm
- ps: npm install -g electron-packager
- ps: make pack; true
- ps: make winstaller; true
artifacts:
- path: out/deplug-win-amd64.exe
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: 5xfEThlejgLcJhJS3rNfbbvFPDyuRy+wVgC0/KrbMiWycAYQej7GhAbCVvSneLoT
  artifact: out/deplug-win-amd64.exe
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
