version: 1.0.{build}
init:
- ps: Install-Product node 8.6.0 x64
environment:
  CL: -DDELAYIMP_INSECURE_WRITABLE_HOOKS
install:
- ps: Start-FileDownload 'https://static.rust-lang.org/rustup/dist/x86_64-pc-windows-msvc/rustup-init.exe'
- rustup-init.exe /VERYSILENT /NORESTART /DIR="C:\Program Files\Rust"
- SET PATH=%PATH%;C:\Program Files\Rust\bin
- rustc -V
- cargo -V
- ps: git submodule update --init --recursive; true
- ps: npm install; true
- ps: npm install -g eslint eslint-plugin-mocha
build_script:
- ps: npm run build; true
test_script:
- ps: eslint .
- ps: npm test
after_test:
- ps: npm install -g npm modclean
- ps: npm prune --production
- ps: node scripts/generate-license-json.js
- ps: npm install; true
- ps: modclean --run
- ps: node scripts/pack.js; true
- ps: node scripts/winstaller.js
- ps: mv out/DeplugSetup.exe out/deplug-win-amd64.exe
artifacts:
- path: out/deplug-win-amd64.exe
deploy:
  release: $(APPVEYOR_REPO_TAG_NAME)
  provider: GitHub
  auth_token:
    secure: 5xfEThlejgLcJhJS3rNfbbvFPDyuRy+wVgC0/KrbMiWycAYQej7GhAbCVvSneLoT
  artifact: out/deplug-win-amd64.exe
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
