[package]
name = "eth"
version = "0.1.0"
authors = ["Ron Hashimoto <mail@h2so5.net>"]

[lib]
name = "main"
crate-type = ["cdylib"]

[dependencies]
libc = "*"
lazy_static = "1.0"
byteorder = "1"
plugkit = { path = "../../plugkit/plugkit-rust" }
